export const v_casings = [
  ["brand_name", "Brand Name"],
  ["casing_type", "Casing Type"],
  ["colors", "Colors"],
  ["drive_bays", "Drive Bays"],
  ["dust_cover", "Dust Cover"],
  ["expansion_slot", "Expansion Slot"],
  ["fan_slots", "Fan Slots"],
  ["height_mm", "Height (mm)"],
  ["io_port", "IO Port"],
  ["length_mm", "Length (mm)"],
  ["max_cpu_cooler_length_mm", "Max CPU Cooler Length (mm)"],
  ["max_gpu_length_mm", "Max GPU Length (mm)"],
  ["max_psu_length_mm", "Max PSU Length (mm)"],
  ["mobo_supports", "Mobo Supports"],
  ["side_panel", "Side Panel"],
  ["weight_kg", "Weight (Kg)"],
  ["width_mm", "Width (mm)"],
];

export const v_cpus = [
  ["base_clock_ghz", "Base Clock (GHz)"],
  ["base_power_watt", "Base Power (Watt)"],
  ["brand_name", "Brand Name"],
  ["code_name", "Code Name"],
  ["cpu_socket", "CPU Socket"],
  ["efficiency_core", "Efficiency Core"],
  ["integrated_gpu", "Integrated GPU"],
  ["max_clock_ghz", "Max Clock (GHz)"],
  ["max_memory_channel", "Max Memory Channel"],
  ["max_memory_gb", "Max Memory (GB)"],
  ["max_power_watt", "Max Power (Watt)"],
  ["model_line", "Model Line"],
  ["performance_core", "Performance Core"],
  ["total_core", "Total Core"],
  ["total_thread", "Total Thread"],
];

export const v_gpus = [
  ["base_clock_mhz", "Base Clock (MHz)"],
  ["boost_clock_mhz", "Boost Clock (MHz)"],
  ["brand_name", "Brand Name"],
  ["bus_interface", "Bus Interface"],
  ["chipset", "Chipset"],
  ["core_count", "Core Count"],
  ["gpu_memory_type", "GPU Memory Type"],
  ["height_mm", "Height (mm)"],
  ["length_mm", "Length (mm)"],
  ["memory_bus_bit", "Memory Bus Bit"],
  ["min_psu_watt", "Min PSU (Watt)"],
  ["tdp_watt", "TDP (Watt)"],
  ["vram_gb", "VRAM (GB)"],
  ["width_mm", "Width (mm)"],
];

export const v_memories = [
  ["amount", "Amount"],
  ["brand_name", "Brand Name"],
  ["capacity_gb", "Capacity (GB)"],
  ["frequency_mhz", "Frequency (MHz)"],
  ["has_ecc", "Has ECC"],
  ["has_heatsink", "Has Heatsink"],
  ["has_rgb", "Has RGB"],
  ["memory_type", "Memory Type"],
  ["overclocked", "Overclocked"],
  ["voltage", "Voltage"],
];

export const v_motherboards = [
  ["back_pannel_ports", "Back Panel Ports"],
  ["brand_name", "Brand Name"],
  ["chipset", "Chipset"],
  ["cpu_socket", "CPU Socket"],
  ["cpu_socket_support", "CPU Socket Support"],
  ["form_factor", "Form Factor"],
  ["memory_channel_count", "Memory Channel Count"],
  ["memory_frequency_mhz", "Memory Frequency (MHz)"],
  ["max_memory_gb", "Max Memory (GB)"],
  ["memory_slot", "Memory Slot"],
  ["memory_type", "Memory Type"],
  ["pcie_m2_slot", "PCIE M2 Slot"],
  ["pcie_slots", "PCIE Slots"],
  ["sata3_slot", "SATA3 Slot"],
  ["wifi_network", "WiFi Network"],
];

export const v_power_supplies = [
  ["brand_name", "Brand Name"],
  ["cpu_connector", "CPU Connector"],
  ["efficiency_rating", "Efficiency Rating"],
  ["form_factor", "Form Factor"],
  ["modularity", "Modularity"],
  ["peripherals_connector", "Peripherals Connector"],
  ["protection", "Protection"],
  ["rgb_connector", "RGB Connector"],
  ["vga_connector", "VGA Connector"],
  ["wattage", "Wattage"],
];

export const v_internal_storages = [
  ["brand_name", "Brand Name"],
  ["capacity_gb", "Capacity (GB)"],
  ["description", "Description"],
  ["form_factor", "Form Factor"],
  ["interface", "Interface"],
  ["lowest_price", "Lowest Price"],
  ["product_id", "Product ID"],
  ["product_name", "Product Name"],
  ["read_speed_mbs", "Read Speed (MB/s)"],
  ["type", "Type"],
  ["write_speed_mbs", "Write Speed (MB/s)"],
];
export const v_monitors = [
  ["brand_name", "Brand Name"],
  ["panel_type", "Panel Type"],
  ["resolution", "Resolution"],
  ["aspect_ratio", "Aspect Ratio"],
  ["size_inch", "Size (inch)"],
  ["srgb_percentage", "Srgb (%)"],
  ["refresh_rate_hz", "Refresh Rate (Hz)"],
  ["brightness_nits", "Brightness (nits)"],
  ["has_speaker", "Built-in Speaker"],
  ["inputs", "Input Port"],
  ["vesa_mount_mm", "Vesa Mount (mm)"],
  ["warranty_years", "Warranty (year/s)"],
  ["spesial_features", "Special Feature"],
];

export const v_spec: Record<string, string[][] | undefined> = {
  headphone: undefined,
  keyboard: undefined,
  mouse: undefined,
  speaker: undefined,
  webcam: undefined,
  printer: undefined,
  monitor: v_monitors,
  os: undefined,
  soundcard: undefined,
  wirednetwork: undefined,
  wirelessnetwork: undefined,
  cable: undefined,
  externaldrive: undefined,
  motherboard: v_motherboards,
  cpu: v_cpus,
  gpu: v_gpus,
  memory: v_memories,
  cooler: undefined,
  psu: v_power_supplies,
  storage: v_internal_storages,
  casing: v_casings,
  casefan: undefined,
};
